# https://docs.gitlab.com/ee/ci/quick_start/README.html
# https://docs.gitlab.com/runner/install/docker.html
default:
  image: ubuntu:18.04
  before_script:
    - apt-get update -y
    - apt-get install -y build-essential

job-build-emacs:
  script:
    - make
    - make install-data-local

job-run-emacs:
  script:
    - ./bin/emacs-compile.sh
    - emacs --version
